locals {
  # one() returns null when the list is empty (module count = 0), never errors
  instance_public_ip = (
    var.cloud_provider == "aws"
    ? one(module.aws[*].instance_public_ip)
    : (
      var.cloud_provider == "digitalocean"
      ? one(module.digitalocean[*].instance_public_ip)
      : one(module.hetzner[*].instance_public_ip)
    )
  )

  openclaw_url = !local.openclaw_enabled ? "disabled" : (
    var.public_domain_enabled && local.resolved_openclaw_domain != ""
    ? "https://${local.resolved_openclaw_domain}"
    : (
      var.tailscale_enabled
      ? "https://${var.project_name}  (via Tailscale Serve, mode=${var.tailscale_mode} — connect your device to the same tailnet first)"
      : "http://localhost:18789  (after running the SSH tunnel shown in tailscale_note)"
    )
  )

  hermes_url = !local.hermes_enabled ? "disabled" : (
    var.public_domain_enabled && local.resolved_hermes_domain != ""
    ? "https://${local.resolved_hermes_domain}"
    : "http://localhost:9119  (after running: ssh -L 9119:127.0.0.1:9119 ${var.admin_username}@${local.instance_public_ip})"
  )

  n8n_url = !local.n8n_enabled ? "disabled" : (
    var.public_domain_enabled && local.resolved_n8n_domain != ""
    ? "https://${local.resolved_n8n_domain}"
    : "http://localhost:5678  (after running: ssh -L 5678:127.0.0.1:5678 ${var.admin_username}@${local.instance_public_ip})"
  )

  n8n_webhook_url = !local.n8n_enabled ? "disabled" : (
    var.public_domain_enabled && local.resolved_n8n_domain != ""
    ? "https://${local.resolved_n8n_domain}/webhook"
    : "http://localhost:5678/webhook  (after running the n8n SSH tunnel)"
  )

}

output "provider_used" {
  description = "Cloud provider that was deployed."
  value       = var.cloud_provider
}

output "instance_public_ip" {
  description = "Public IP address of the server."
  value       = local.instance_public_ip
}

output "ssh_command" {
  description = "SSH command to connect to the instance."
  value       = "ssh ${var.admin_username}@${local.instance_public_ip}"
}

output "repo_ssh_command" {
  description = "Repo-local SSH wrapper command (uses ./bin/agent-stack-ssh and reads host from Terraform outputs)."
  value       = "./bin/agent-stack-ssh"
}

output "repo_ssh_config_path" {
  description = "Path to the repo-local SSH config file generated by terraform apply (if enabled)."
  value       = var.generate_repo_ssh_config ? "./.ssh/config" : "disabled"
}

output "host_codex_login_command" {
  description = "Run after apply to authenticate the host Codex CLI as the admin user with device auth."
  value       = var.host_codex_cli_enabled ? "ssh ${var.admin_username}@${local.instance_public_ip} 'codex login --device-auth'" : "disabled"
}

output "resolved_ssh_public_key_source" {
  description = "Where the effective ssh_public_key came from: tfvars_or_env, existing_public_key, derived_from_private_key, or generated_new_keypair."
  value       = local.resolved_ssh_key_source
}

output "tailscale_note" {
  description = "Tailscale access information."
  value = var.tailscale_enabled ? (
    local.openclaw_enabled ? "Tailscale is enabled in ${var.tailscale_mode} mode. Once the instance boots (~2 min), device '${var.project_name}' should appear in your Tailscale admin console. OpenClaw is published with Tailscale Serve: https://${var.project_name} (or use dashboard_url_with_token_import for first-time auto-auth)." : "Tailscale is enabled in ${var.tailscale_mode} mode. OpenClaw is disabled, so no Tailscale Serve route is configured by default."
    ) : (
    "Tailscale is DISABLED. Use an SSH tunnel to reach the dashboard: ssh -L 18789:127.0.0.1:18789 ${var.admin_username}@${local.instance_public_ip}  then open http://localhost:18789"
  )
}

output "dashboard_url" {
  description = "OpenClaw dashboard URL (accessible after bootstrap completes, ~2-3 min after apply)."
  value       = local.openclaw_url
}

output "dashboard_url_with_token_import" {
  description = "First-time login URL that auto-imports the gateway token into Control UI via #token fragment."
  value = !local.openclaw_enabled ? "disabled" : (
    var.public_domain_enabled && local.resolved_openclaw_domain != ""
    ? nonsensitive("https://${local.resolved_openclaw_domain}/#token=${local.resolved_gateway_token}")
    : (
      var.tailscale_enabled
      ? nonsensitive("https://${var.project_name}/#token=${local.resolved_gateway_token}")
      : nonsensitive("http://localhost:18789/#token=${local.resolved_gateway_token}  (after running the SSH tunnel shown in tailscale_note)")
    )
  )
}

output "workspace_ssh_command" {
  description = "SSH command for the optional workspace container over Tailscale."
  value       = local.workspace_enabled ? "ssh -p ${var.workspace_ssh_host_port} ${var.workspace_username}@${var.project_name}" : "disabled"
}

output "workspace_codex_login_command" {
  description = "Run inside the optional workspace container to authenticate Codex with device auth."
  value       = local.workspace_enabled ? "ssh -p ${var.workspace_ssh_host_port} ${var.workspace_username}@${var.project_name} 'codex login --device-auth'" : "disabled"
}

output "workspace_note" {
  description = "Workspace access notes."
  value = local.workspace_enabled ? (
    var.tailscale_enabled && var.tailscale_mode == "host"
    ? "Workspace is enabled. Connect over the tailnet with workspace_ssh_command, then run workspace_codex_login_command. Password auth is enabled only inside the workspace container; no Docker socket is mounted."
    : "Workspace is enabled, but the intended supported access path is tailscale_enabled=true with tailscale_mode=\"host\"."
  ) : "disabled"
}

output "vpn_note" {
  description = "Host VPN egress status and diagnostics hint."
  value = var.vpn_enabled ? (
    "Host VPN is enabled with provider ${var.vpn_provider}. Docker service egress should route through agent-stack-vpn.service; verify with: agent-stack-diagnostics health vpn"
  ) : "disabled"
}

output "gateway_token" {
  description = "Gateway token used by OpenClaw Control UI and WebSocket auth."
  value       = nonsensitive(local.resolved_gateway_token)
}

output "pair_latest_command" {
  description = "Run after opening dashboard_url_with_token_import to approve the latest pending paired-device request."
  value       = local.openclaw_enabled ? "ssh ${var.admin_username}@${local.instance_public_ip} 'docker compose -f /opt/agent-stack/docker-compose.yml exec -T openclaw openclaw devices approve --latest --token ${nonsensitive(local.resolved_gateway_token)} --url ws://127.0.0.1:18789'" : "disabled"
}

output "repo_pair_latest_command" {
  description = "Repo-local wrapper command to approve the latest pending paired-device request."
  value       = local.openclaw_enabled ? "./bin/agent-stack-ssh -- docker compose -f /opt/agent-stack/docker-compose.yml exec -T openclaw openclaw devices approve --latest --token ${nonsensitive(local.resolved_gateway_token)} --url ws://127.0.0.1:18789" : "disabled"
}

output "whatsapp_login_command" {
  description = "Interactive command to link WhatsApp by scanning QR from your terminal."
  value       = local.openclaw_enabled ? "ssh -t ${var.admin_username}@${local.instance_public_ip} 'docker compose -f /opt/agent-stack/docker-compose.yml exec openclaw openclaw channels login --channel whatsapp --verbose'" : "disabled"
}

output "bootstrap_log_command" {
  description = "Command to watch the bootstrap log on the server."
  value       = "ssh ${var.admin_username}@${local.instance_public_ip} 'tail -f /var/log/openclaw-bootstrap.log'"
}

output "repo_bootstrap_log_command" {
  description = "Repo-local wrapper command to watch bootstrap logs."
  value       = "./bin/agent-stack-ssh -- tail -f /var/log/openclaw-bootstrap.log"
}

output "openclaw_url" {
  description = "OpenClaw UI URL or access hint."
  value       = local.openclaw_url
}

output "hermes_url" {
  description = "Hermes dashboard URL or access hint."
  value       = local.hermes_url
}

output "n8n_url" {
  description = "n8n UI URL or access hint."
  value       = local.n8n_url
}

output "n8n_webhook_url" {
  description = "n8n webhook base URL or access hint."
  value       = local.n8n_webhook_url
}

output "ui_auth_username" {
  description = "Username for the public-domain reverse-proxy login."
  value       = var.public_domain_enabled ? var.ui_auth_username : "disabled"
}

output "ui_auth_password" {
  description = "Password for the public-domain reverse-proxy login."
  value       = var.public_domain_enabled ? local.resolved_ui_auth_password : "disabled"
  sensitive   = true
}
