locals {
  # one() returns null when the list is empty (module count = 0), never errors
  instance_public_ip = (
    var.cloud_provider == "aws"
    ? one(module.aws[*].instance_public_ip)
    : one(module.digitalocean[*].instance_public_ip)
  )
}

output "provider_used" {
  description = "Cloud provider that was deployed."
  value       = var.cloud_provider
}

output "instance_public_ip" {
  description = "Public IP address of the server."
  value       = local.instance_public_ip
}

output "ssh_command" {
  description = "SSH command to connect to the instance."
  value       = "ssh ${var.admin_username}@${local.instance_public_ip}"
}

output "repo_ssh_command" {
  description = "Repo-local SSH wrapper command (uses ./bin/cloud-claw-ssh and reads host from Terraform outputs)."
  value       = "./bin/cloud-claw-ssh"
}

output "repo_ssh_config_path" {
  description = "Path to the repo-local SSH config file generated by terraform apply (if enabled)."
  value       = var.generate_repo_ssh_config ? "./.ssh/config" : "disabled"
}

output "resolved_ssh_public_key_source" {
  description = "Where the effective ssh_public_key came from: tfvars_or_env, existing_public_key, derived_from_private_key, or generated_new_keypair."
  value       = local.resolved_ssh_key_source
}

output "tailscale_note" {
  description = "Tailscale access information."
  value = var.tailscale_enabled ? (
    "Tailscale is enabled. Once the instance boots (~2 min), the sidecar device '${var.project_name}' should appear in your Tailscale admin console. Dashboard is published with Tailscale Serve: https://${var.project_name} (or use dashboard_url_with_token_import for first-time auto-auth)."
    ) : (
    "Tailscale is DISABLED. Use an SSH tunnel to reach the dashboard: ssh -L 18789:127.0.0.1:18789 ${var.admin_username}@${local.instance_public_ip}  then open http://localhost:18789"
  )
}

output "dashboard_url" {
  description = "OpenClaw dashboard URL (accessible after bootstrap completes, ~2-3 min after apply)."
  value = var.tailscale_enabled ? (
    "https://${var.project_name}  (via Tailscale Serve sidecar — connect your device to the same tailnet first)"
    ) : (
    "http://localhost:18789  (after running the SSH tunnel shown in tailscale_note)"
  )
}

output "dashboard_url_with_token_import" {
  description = "First-time login URL that auto-imports the gateway token into Control UI via #token fragment."
  value = var.tailscale_enabled ? (
    nonsensitive("https://${var.project_name}/#token=${local.resolved_gateway_token}")
    ) : (
    nonsensitive("http://localhost:18789/#token=${local.resolved_gateway_token}  (after running the SSH tunnel shown in tailscale_note)")
  )
}

output "gateway_token" {
  description = "Gateway token used by OpenClaw Control UI and WebSocket auth."
  value       = nonsensitive(local.resolved_gateway_token)
}

output "pair_latest_command" {
  description = "Run after opening dashboard_url_with_token_import to approve the latest pending paired-device request."
  value       = "ssh ${var.admin_username}@${local.instance_public_ip} 'docker exec openclaw-openclaw-1 openclaw devices approve --latest --token ${nonsensitive(local.resolved_gateway_token)} --url ws://127.0.0.1:18789'"
}

output "repo_pair_latest_command" {
  description = "Repo-local wrapper command to approve the latest pending paired-device request."
  value       = "./bin/cloud-claw-ssh -- docker exec openclaw-openclaw-1 openclaw devices approve --latest --token ${nonsensitive(local.resolved_gateway_token)} --url ws://127.0.0.1:18789"
}

output "whatsapp_login_command" {
  description = "Interactive command to link WhatsApp by scanning QR from your terminal."
  value       = "ssh -t ${var.admin_username}@${local.instance_public_ip} 'sudo docker exec -it openclaw-openclaw-1 openclaw channels login --channel whatsapp --verbose'"
}

output "bootstrap_log_command" {
  description = "Command to watch the bootstrap log on the server."
  value       = "ssh ${var.admin_username}@${local.instance_public_ip} 'tail -f /var/log/openclaw-bootstrap.log'"
}

output "repo_bootstrap_log_command" {
  description = "Repo-local wrapper command to watch bootstrap logs."
  value       = "./bin/cloud-claw-ssh -- tail -f /var/log/openclaw-bootstrap.log"
}
